spring:
  application:
    name: discoveryserver

server:
  port: 0

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:0/eureka/

  instance:
    hostname: localhost
