spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: catalogservice
            uri: lb://catalogservice
            predicates:
              - Path=/api/v1/catalogproductoffers/**
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true              